spring:
  application:
    name: marginality2

  profiles:
    active: default

  r2dbc:
    url: ${DATABASE_URL:r2dbc:h2:file:///./data/prod;DB_CLOSE_DELAY=-1}
    username: sa
    password: ""


  flyway:
    url: jdbc:h2:file:./data/prod
    user: sa
    password: ""
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true  # Позволяет использовать Flyway с существующими базами данных
    sql-migration-prefix: V  # Префикс для SQL-скриптов миграции (например, V1__init.sql)
    clean-disabled: true  # Запрещает очистку базы данных через Flyway (для безопасности)
  docker:
    compose:
      enabled: false

  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.r2dbc.core: DEBUG  # Логирование запросов R2DBC
    org.springframework.data.r2dbc: DEBUG  # Логирование операций с данными через Spring Data R2DBC
    org.flywaydb: DEBUG