spring:
  application:
    name: marginality2

  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

#  jpa:
    # hibernate.ddl-auto: update   # Закомментировано, так как не используется
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect

  docker:
    compose:
      enabled: false

# h2:
#   console:
#     enabled: true

# logging:
#   level:
#     org:
#       springframework:
#         data:
#           r2dbc: DEBUG
#     io:
#       r2dbc:
#         spi: DEBUG
#         pool: DEBUG